### ISSUE TITLE
Bitget Wallet campaign UI support

### ISSUE THREAD

**Issue by tomjeatt** [bob-collective/ui#93]
**Tasks**

- [ ] Add BitgetWallet as an option in the UI https://github.com/bob-collective/ui/pull/109
- [ ] Adjust the minimum transferable BTC amount https://github.com/bob-collective/ui/pull/108
- [ ] Test transfers from desktop
- [ ] Test ERC20 transfers from 

-------------------

See here: 
https://www.notion.so/build-on-bitcoin/Bitget-Tech-requirement-d7a04e50f0f743f4b4639d6ff6427fac?pvs=4

We are still waiting on Zhixi to finalise date and tasks (tasks have been handed over to Bitget—waiting for their sign off) so there is a chance there may be additional work not listed here. @gregdhill will coordinate.

The only task which will be carried out on our app is:

> Onramp any amount over 30USD worth of BTC from BTC mainnet to BOB using BOB Gateway. 

On the UI side there are four things needed:

1. Add Bitget Wallet to the list of EVM wallet options. (Bitget is already listed under Bitcoin wallets).
![Image](https://github.com/user-attachments/assets/112e3cda-80cd-43f4-b238-96802973586c)

2. Test that the bridge works in desktop browsers. This can be done on testnet.

3. Test that the bridge works in the Bitget Wallet app on both Android and iOS devices, for both BTC and ERC20 transactions.
    - This has to be done on mainnet—Bitget cannot support Sepolia in their app.
    - I have already tested BTC transactions on iOS (iPhone 15 pro, iOS 17.5.1).
    - This is something that will need to be coordinated with the rest of the team, so that we test as many devices/OS versions as possible.

ERC20 transfers are not one of the tasks, but we want to encourage Bitget Wallet users to use our app so we should make sure they work.

4. Adjust the minimum transferable BTC amount, which is currently set to approx. $185:
https://github.com/bob-collective/ui/blob/main/apps/evm/src/pages/Bridge/components/BridgeForm/BtcBridgeForm.tsx#L44

**Comment by tomjeatt** [comment]
- [ ]
